################################################################
# Entrypoints configuration
################################################################
# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.websecure]
    address = ":443"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
[log]
  level = "INFO"

################################################################
# API and dashboard configuration
################################################################
# Enable API and dashboard
[api]
  insecure = true
  dashboard = true

################################################################
# Docker configuration backend
################################################################
# Enable Docker configuration backend
[providers.docker]
  exposedByDefault = false
# dynamic files config
[providers.file]
    directory = "/etc/traefik"
    watch = true
    filename = "rules.toml"
    debugLogGeneratedTemplate = true
     